name: CD
on:
    push:
    pull_request:
    workflow_dispatch:
    workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENLANE_ROOT:       /home/runner/work/caravel_mpw/openlane
      PDK_ROOT:            /home/runner/work/caravel_mpw/openlane/pdks
      CARAVEL_ROOT:        /home/runner/work/caravel_mpw/caravel_mpw/caravel
      OPENLANE_IMAGE_NAME: efabless/openlane:2021.11.23_01.42.34
      OPENLANE_TAG:        2021.11.23_01.42.34
      CARAVEL_TAG:         mpw-5a
      MAGIC_VERSION:       8.3.265
      MCW:                 PICO
    steps:
       - uses: actions/checkout@v2
       - name: debug
         run:  |
           echo ${{ github.event_name }}
       - name: install deps
         run:  bash .github/scripts/build/run-install-magic.sh
       - name: install caravel
         run:  |
           make install
           make install_mcw
           make openlane
           make pdk-with-sram
       - name: uncompress
         run:  make uncompress
       - name: build user gds
         run: |
           bash .github/scripts/build/build-user.sh \
           || bash .github/scripts/build/build-user.sh \
           || bash .github/scripts/build/build-user.sh \
           || bash .github/scripts/build/build-user.sh \
           || bash .github/scripts/build/build-user.sh
       - name: build wrapper gds
         run: |
           bash .github/scripts/build/build-wrapper.sh \
           || bash .github/scripts/build/build-wrapper.sh \
           || bash .github/scripts/build/build-wrapper.sh \
           || bash .github/scripts/build/build-wrapper.sh \
           || bash .github/scripts/build/build-wrapper.sh
       - name: compress
         run:  make compress
       - name: push
         #if: github.event_name == 'workflow_dispatch'
         run: |
           ls -la
           git status
           git add def gds lef mag maglef signoff verilog spi
           git status
           git config user.email "rbacik@hotmail.com"
           git config user.name "roman3017"
           git commit -m "action: update build"
           git push origin HEAD:main
